### ISSUE TITLE
perf_lists.py not python3 compatible

### ISSUE THREAD

**Issue by thisch** [appnexus/pyrobuf#130]
```
$> python tests/perf_lists.py
list took 0.190504 seconds
TypedList took 0.554765 seconds
DoubleList took 0.281462 seconds
FloatList took 0.274609 seconds
array 'f' took 0.293115 seconds
Traceback (most recent call last):
  File "tests/perf_lists.py", line 140, in <module>
    main()
  File "tests/perf_lists.py", line 77, in main
    for i in xrange(1000000):
NameError: name 'xrange' is not defined
```

**Comment by tburmeister** [comment]
Good catch @thisch ! I just merged in a fix.
