### ISSUE TITLE
Support for the ``syntax`` field

### ISSUE THREAD

**Issue by claws** [appnexus/pyrobuf#38]
As there are versions 2 and 3 of protobuf it seems that a ``syntax`` option is used to declare which version is being used, e.g. ``syntax = "proto3";``. This is mentioned [here](https://developers.google.com/protocol-buffers/docs/proto3#simple). I don't see the field explicitly mentioned in the version 2 spec. It seems that by default a parser should assume version 2 unless told that the syntax is version 3.

I am trying to process a file from the Prometheus client model project (the ``[metrics.proto](https://github.com/prometheus/client_model/blob/master/metrics.proto)`` and pyrobuf is not parsing the ``.proto`` file and reports:
```
$ python -m pyrobuf metrics.proto 
generating metrics.proto
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/path/to/my/venv/lib/python3.5/site-packages/pyrobuf-0.5.8-py3.5-macosx-10.6-intel.egg/pyrobuf/__main__.py", line 90, in <module>
    main()
  File "/path/to/my/venv/lib/python3.5/site-packages/pyrobuf-0.5.8-py3.5-macosx-10.6-intel.egg/pyrobuf/__main__.py", line 18, in main
    gen_message(args.source, out=args.out_dir, build=args.build_dir, install=args.install)
  File "/path/to/my/venv/lib/python3.5/site-packages/pyrobuf-0.5.8-py3.5-macosx-10.6-intel.egg/pyrobuf/__main__.py", line 62, in gen_message
    generate(fname, out, parser, templ_pxd, templ_pyx)
  File "/path/to/my/venv/lib/python3.5/site-packages/pyrobuf-0.5.8-py3.5-macosx-10.6-intel.egg/pyrobuf/__main__.py", line 80, in generate
    msgdef = parser.parse_from_filename(fname)
  File "/path/to/my/venv/lib/python3.5/site-packages/pyrobuf-0.5.8-py3.5-macosx-10.6-intel.egg/pyrobuf/parse_proto.py", line 185, in parse_from_filename
    return self.parse(s, fname=fname)
  File "/path/to/my/venv/lib/python3.5/site-packages/pyrobuf-0.5.8-py3.5-macosx-10.6-intel.egg/pyrobuf/parse_proto.py", line 151, in parse
    for token in tokens:
  File "/path/to/my/venv/lib/python3.5/site-packages/pyrobuf-0.5.8-py3.5-macosx-10.6-intel.egg/pyrobuf/parse_proto.py", line 143, in tokenize
    raise Exception("Unexpected character '%s' in line %d: '%s'" % (s[pos], line, s[pos-10:pos+10]))
Exception: Unexpected character 's' in line 2: 'License.

syntax = "'
```

If I comment out the ``syntax = "proto2";`` line the parsing progresses further. I am not sure if syntax is really an option but it appears that people are using it and the standard protobuf compiler does not have issues with it. It would be useful to to mirror the behaviour of the C++ protobuf compiler as close as possible.

**Comment by claws** [comment]
I took a quick look and something like this seems to work for the file I'm parsing. 

``` diff
diff --git a/pyrobuf/parse_proto.py b/pyrobuf/parse_proto.py
index 601ee35..27b6346 100644
--- a/pyrobuf/parse_proto.py
+++ b/pyrobuf/parse_proto.py
@@ -21,7 +21,8 @@ class Parser(object):
         'RBRACE': r'\}',
         'SKIP': r'[ \t]',
         'NEWLINE': r'[\r\n]',
-        'PACKAGE': r'package\s.*;'
+        'PACKAGE': r'package\s.*;',
+        'SYNTAX': r'(syntax\s+.*?);'
     }
 
     scalars = (
@@ -106,6 +107,9 @@ class Parser(object):
             if token_type == 'OPTION':
                 yield ParserOption(pos, *vals)
 
+            elif token_type == 'SYNTAX':
+                yield ParserSyntax(pos, *vals)
+
             elif token_type == 'IMPORT':
                 yield ParserImport(pos, *vals)
 
@@ -152,6 +156,12 @@ class Parser(object):
             if token.token_type == 'OPTION':
                 continue
 
+            elif token.token_type == 'SYNTAX':
+                if 'proto2' not in token.value:
+                    raise Exception(
+                        'Only proto2 is currently supported')
+                continue
+
             elif token.token_type == 'IMPORT':
                 rep['imports'].append(token.value)
 
@@ -317,6 +327,13 @@ class ParserOption(object):
         self.option = option
 
 
+class ParserSyntax(object):
+    def __init__(self, pos, value):
+        self.token_type = 'SYNTAX'
+        self.pos = pos
+        self.value = value
+
+
 class ParserImport(object):
     def __init__(self, pos, value):
         self.token_type = 'IMPORT'

```

**Comment by 3kwa** [comment]
Could you submit a PR, ideally with a minimal test?

That's how I would have tackled it too ;)

EuGeNe -- follow me on http://twitter.com/3kwa

**Comment by claws** [comment]
Just submitted a PR.
