### ISSUE TITLE
Problem passing in lists for repeated fields

### ISSUE THREAD

**Issue by claws** [appnexus/pyrobuf#48]
I am encountering an error whenever I pass a list of Protocol Buffer objects in as the value for a repeated field. The error originates in the TypedList ``extend`` method. I am expecting to be able to pass in a list of the appropriate objects. Do I need to wrap the objects in some kind of Pyrobuf TypedList object before passing them in to the constructors?

I have crafted up a short example that demonstrates the issue I am getting.

The protocol buffers content used with this example is contained in the code block below. This is a cut-down version of the original file that contains only the items necessary to demonstrate the problem.
It should be placed into a file called ``prometheus_metrics.proto`` and installed using the standard pyrobuf installed method.

```
message LabelPair {
  optional string name  = 1;
  optional string value = 2;
}

message Counter {
  optional double value = 1;
}

message Metric {
  repeated LabelPair label        = 1;
  optional Counter   counter      = 2;
}
```

``` python
import argparse

from prometheus_metrics_proto import Counter, LabelPair, Metric


ARGS = argparse.ArgumentParser(description='Pyrobuf extend issue demo')
ARGS.add_argument(
    '--work-around', dest='workaround', action="store_true",
    help="Use the work-around method instead")


if __name__ == '__main__':
    args = ARGS.parse_args()

    counter = Counter(value=1)
    label = LabelPair(name='host', value='localhost')

    if args.workaround:
        # Bypassing the constructor, I can pass in the list of
        # LabelPair objects and it now works as I expect.
        metric = Metric(counter=counter)
        metric.label = [label]
    else:
        # I am expecting to be able to pass in a list of LabelPair
        # objects to the ``repeated`` label field, but this causes
        # an error to be raised.
        metric = Metric(label=[label], counter=counter)

    print('labels: {}'.format([(l.name, l.value) for l in metric.label]))
    print(metric.counter)
```

Once the ``prometheus_metrics_proto`` module is installed then the example script can be run. When I run the script I observe an error, as shown below. This kind of error seems to happen whenever I pass a list of Protocol Buffer objects in for any repeated field item.

```
$ python extend-issue.py
Traceback (most recent call last):
  File "pyrobuf/src/pyrobuf_list.pyx", line 64, in pyrobuf_list.TypedList.extend (pyrobuf/src/pyrobuf_list.c:3027)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extend-issue.py", line 26, in <module>
    metric = Metric(label=[label], counter=counter)
  File "pyrobuf/_proto/prometheus_metrics_proto.pyx", line 3186, in prometheus_metrics_proto.Metric.__init__ (pyrobuf/_proto/prometheus_metrics_proto.c:45950)
  File "pyrobuf/src/pyrobuf_list.pyx", line 67, in pyrobuf_list.TypedList.extend (pyrobuf/src/pyrobuf_list.c:3097)
Exception: type mismatch
```

I have found a work around method for now. This simply applies any list additions after the constructor. To run the example script using the work around method pass the ``--work-around`` flag.

```
$ python extend-issue.py --work-around
labels: [('host', 'localhost')]
value: 1.0
```

**Comment by claws** [comment]
@grgsrs I applied your changes from #49 and they fix my issues. Thanks for fixing my issues so quickly!
