### ISSUE TITLE
semicolon after curly brace should be allowed as in protoc

### ISSUE THREAD

**Issue by daa** [appnexus/pyrobuf#54]
Currently pyrobuf forbids semicolon after curly brace in message type definition however google's protoc allows it.

For example, let's take following specification:

```
message M {
    optional string s = 1;

    message Nested {
        required int32 value = 1;
    };
}
```

google protoc succeeds:

```
$ protoc semicolon.proto --python_out=.
$ echo $?
0
```

pyrobuf fails:

```
$ python -m pyrobuf --out-dir y x/semicolon.proto 
generating x/semicolon.proto
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/daa/pyrobuf/pyrobuf/__main__.py", line 90, in <module>
    main()
  File "/home/daa/pyrobuf/pyrobuf/__main__.py", line 18, in main
    gen_message(args.source, out=args.out_dir, build=args.build_dir, install=args.install)
  File "/home/daa/pyrobuf/pyrobuf/__main__.py", line 62, in gen_message
    generate(fname, out, parser, templ_pxd, templ_pyx)
  File "/home/daa/pyrobuf/pyrobuf/__main__.py", line 80, in generate
    msgdef = parser.parse_from_filename(fname)
  File "pyrobuf/parse_proto.py", line 195, in parse_from_filename
    return self.parse(s, fname=fname)
  File "pyrobuf/parse_proto.py", line 175, in parse
    rep['messages'].append(self._parse_message(s, token, tokens, enums, imported['enums']))
  File "pyrobuf/parse_proto.py", line 210, in _parse_message
    for token in tokens:
  File "pyrobuf/parse_proto.py", line 147, in tokenize
    raise Exception("Unexpected character '%s' in line %d: '%s'" % (s[pos], line, s[pos-10:pos+10]))
Exception: Unexpected character ';' in line 6: '= 1;
    };
}
'
```

**Comment by claws** [comment]
It appears that neither the [v2](https://developers.google.com/protocol-buffers/docs/reference/proto2-spec#message_definition) spec or the [v3](https://developers.google.com/protocol-buffers/docs/proto3#nested) spec indicate that a semi colon is expected or optional in the case of nested messages. 

I'm not an expert in protocol buffers. It seems like this is an undocumented aspect of protoc. You could raise a bug on protoc - to either comply with their spec or to add some docs that indicate the trailing semi-colon is optional.

From a compatibility standpoint I guess it would be nice it pyrobuf operated identically to protoc - even if the behaviour is unspecified.
