### ISSUE TITLE
failed when compile proto

### ISSUE THREAD

**Issue by bigtan** [appnexus/pyrobuf#59]
environment info:
python 35 64 bit
wheel compiled from source.
cython 0.24.1
[pyrobuf-0.5.11-cp35-cp35m-win_amd64.whl.zip](https://github.com/appnexus/pyrobuf/files/432972/pyrobuf-0.5.11-cp35-cp35m-win_amd64.whl.zip)

```
out\test_message_proto.pyx:1108:44: Cannot convert 'PyObject *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
            self._another_int_field = 0
        elif field_name == 'substruct_ref':
            self._substruct_ref._listener = <PyObject *>null_listener
            self._substruct_ref = TestRef.__new__(TestRef)
            self._substruct_ref.reset()
            self._substruct_ref._listener = <PyObject *>self
                                           ^
------------------------------------------------------------

out\test_message_proto.pyx:1111:44: Cannot convert 'PyObject *' to Python object
Traceback (most recent call last):
  File "e:\develop\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\develop\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Develop\Python35\Scripts\pyrobuf.exe\__main__.py", line 9, in <module>
  File "e:\develop\python35\lib\site-packages\pyrobuf\__main__.py", line 18, in main
    gen_message(args.source, out=args.out_dir, build=args.build_dir, install=args.install)
  File "e:\develop\python35\lib\site-packages\pyrobuf\__main__.py", line 68, in gen_message
    include_path=[os.path.join(HERE, 'src'), out]),
  File "e:\develop\python35\lib\site-packages\Cython\Build\Dependencies.py", line 915, in cythonize
```

**Comment by grgsrs** [comment]
Hi bigtan,

I was able to replicate the error you're seeing when I attempted to compile the "test_message.proto" file without first compiling the "test_ref_message.proto" file upon which it depends.

So, for example, simply running `pyrobuf --out-dir=out test_message.proto` resulted in the error you described above, but running

```
pyrobuf --out-dir=out test_ref_message.proto
pyrobuf --out-dir=out test_message.proto
```

worked correctly.

**Comment by bigtan** [comment]
thanks @grgsrs
