### ISSUE TITLE
Cannot parse Steam protobuf definitions

### ISSUE THREAD

**Issue by systocrat** [appnexus/pyrobuf#72]
I wrote a bash script to download and compile the protocol buffers included in SteamKit2 with pyrobuf and ended up with a strange error.

The script is as follows:

    #!/bin/bash

    STEAMKIT='https://github.com/SteamRE/SteamKit.git'
    CLONE_TO='./.steamkit/'
    PROTO_FOLDER='./steamclient/protocol/'
    DEFS_FOLDER=$CLONE_TO'Resources/Protobufs/'

    if [ -z $(which git) ]; then
        echo 'Git must be installed and accessible in PATH'
        exit
    fi

    if [ -z $(which pyrobuf) ]; then
        echo 'pyrobuf must be installed and accessible in PATH'
        exit
    fi

    if [ ! -d $PROTO_FOLDER ]; then
        mkdir -p $PROTO_FOLDER
    fi

    git clone --depth 1 "$STEAMKIT" "$CLONE_TO"

    cp -R $DEFS_FOLDER'google' $DEFS_FOLDER'steamclient'

    pyrobuf $DEFS_FOLDER'steamclient'
    
    # rm -rf $CLONE_TO

And the stack trace is:

    Traceback (most recent call last):
      File ",/venv/bin/pyrobuf", line 11, in <module>
        sys.exit(main())
      File "./venv/lib/python2.7/site-packages/pyrobuf/__main__.py", line 18, in main
    generating ./.steamkit/Resources/Protobufs/steamclient/steammessages_base.proto
        gen_message(args.source, out=args.out_dir, build=args.build_dir, install=args.install)
      File "./venv/lib/python2.7/site-packages/pyrobuf/__main__.py", line 51, in gen_message
        generate(spec, out, parser, templ_pxd, templ_pyx)
      File "./venv/lib/python2.7/site-packages/pyrobuf/__main__.py", line 80, in generate
        msgdef = parser.parse_from_filename(fname)
      File "./venv/lib/python2.7/site-packages/pyrobuf/parse_proto.py", line 195, in parse_from_filename
        return self.parse(s, fname=fname)
      File "./venv/lib/python2.7/site-packages/pyrobuf/parse_proto.py", line 170, in parse
        imported_rep = self._parse_import(token.value + '.proto', fname)
      File "./venv/lib/python2.7/site-packages/pyrobuf/parse_proto.py", line 200, in _parse_import
        rep = i_parser.parse_from_filename(actual_fname)
      File "./venv/lib/python2.7/site-packages/pyrobuf/parse_proto.py", line 195, in parse_from_filename
        return self.parse(s, fname=fname)
      File "./venv/lib/python2.7/site-packages/pyrobuf/parse_proto.py", line 175, in parse
        rep['messages'].append(self._parse_message(s, token, tokens, enums, imported['enums']))
      File "./venv/lib/python2.7/site-packages/pyrobuf/parse_proto.py", line 210, in _parse_message
        for token in tokens:
      File "./venv/lib/python2.7/site-packages/pyrobuf/parse_proto.py", line 147, in tokenize
        raise Exception("Unexpected character '%s' in line %d: '%s'" % (s[pos], line, s[pos-10:pos+10]))
    Exception: Unexpected character ';' in line 62: 'oding.
      };
    
Line 62 of that particular file can be seen on GitHub here: https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/steamclient/steammessages_base.proto#L62

I'm not sure if this is a pyrobuf bug or if I'm using pyrobuf improperly, I would appreciate any guidance I can get.

Thank you!

**Comment by tburmeister** [comment]
I think the parsing issue has been fixed - I don't get the error shown - but the install still fails because Pyrobuf can't process the import statement. I get:
```
FileNotFoundError: [Errno 2] No such file or directory: 'proto/google/protobuf/descriptor.proto'
```
This is not something I think we will be able to support.
