### ISSUE TITLE
pyrobuf 0.5.11 not compatible with python 3.6.2

### ISSUE THREAD

**Issue by vogt31337** [appnexus/pyrobuf#74]
## -- "conda list" --
pip                       9.0.1                    py36_1
python                    3.6.2                         0
setuptools                27.2.0                   py36_1
vs2015_runtime            14.0.25420                    0
wheel                     0.29.0                   py36_0

## -- "python -V" --
Python 3.6.2 :: Continuum Analytics, Inc.

## -- "machine" --
Windows 7 x86_64

## -- "pip install pyrobuf" --

Exception:
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 137: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Anaconda3\envs\py3.6\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 137: invalid start byte

**Comment by tburmeister** [comment]
I'm able to pip install, build messages, and use on my Mac with Python 3.6.2, so perhaps this is just a Windows issue?

**Comment by vogt31337** [comment]
I don't know and I don't quite understand the error. But it keeps happening with python 3.6.6...

Okay found a 'fix'; seems to be a problem with pip (and windows):
"C:\Anaconda3\envs\py3.6\lib\site-packages\pip\compat_init_.py" Line 75
Change decoding from 'utf-8' to 'cp1251' and then it works.

Closing due to no pyrobuf relation.

**Comment by mevinbabuc** [comment]
This happens to me too. I have a mac with anaconda python 3.6 and I see this error when trying to read a protobuf log file generated by appnexus. I haven't tried it on any other file

**Comment by yutiansut** [comment]
nono  it just a problem caused by pip.
