### ISSUE TITLE
field defined as bytes can't serialize

### ISSUE THREAD

**Issue by tperkinson** [appnexus/pyrobuf#8]
Inside of proto file a field is defined as:

optional bytes payload = 7;

Using the .so (mac), serializing the object to JSON (myprotobug.SerializeToJson() for example) produces the following error (obfuscating file names):

File "out/xxxxxxxx.pyx", line 134, in xxxxxx.xxx.SerializeToJson (out/xxxxxx_proto.c:2687)
  File "out/xxxxx.pyx", line 168, in xxxxx.xxxx.SerializeToDict (out/xxxxx.c:3248)
  File "out/xxxx.pyx", line 649, in xxxx.xxxx.SerializeToDict (out/xxxx.c:9543)
  File "out/xxxxx.pyx", line 686, in xxxx.yyyy.SerializeToDict (out/yyyy.c:10270)
AttributeError: 'str' object has no attribute 'SerializeToDict'

When I search the pyx, line 686 is:
payload_dict = self.payload.SerializeToDict()

Are bytes implemented?

**Comment by tperkinson** [comment]
Simplifying:

demo_c_message.proto contains:
message C{
        optional bytes payload = 1;
        }

python code:
import demo_c_message_proto
c = demo_c_message_proto.C()
c.SerializeToJson()

Traceback (most recent call last):
  File "/Users/tperkinson/Documents/workspace/PROTOS/checkdemoC.py", line 9, in <module>
    c.SerializeToJson()
  File "out/demo_c_message_proto.pyx", line 122, in demo_c_message_proto.C.SerializeToJson (out/demo_c_message_proto.c:2353)
  File "out/demo_c_message_proto.pyx", line 152, in demo_c_message_proto.C.SerializeToDict (out/demo_c_message_proto.c:2749)
AttributeError: 'str' object has no attribute 'SerializeToDict'

**Comment by grgsrs** [comment]
This should be fixed now @tperkinson. Can you confirm?

**Comment by tperkinson** [comment]
My test case passes!!! Thank you!
