### ISSUE TITLE
Message containing underscore won't compile

### ISSUE THREAD

**Issue by vstax** [appnexus/pyrobuf#86]
Python 2.7, proto 2 syntax, minimal example:
```
package test;

message Test {
    message Underscore_test {
        optional uint32 age                 = 3;
    }
    optional Underscore_test underscore = 10;
}
```

Compiles fine by Google protobuf compiler 2.6.1 or 3.3.1 in proto2 mode but doesn't compile by pyrobuf 0.6.3 (latest version installed by pip):
```
$ pyrobuf test.proto 
generating test.proto
Traceback (most recent call last):
  File "/usr/bin/pyrobuf", line 11, in <module>
    load_entry_point('pyrobuf==0.6.3', 'console_scripts', 'pyrobuf')()
  File "/usr/lib64/python2.7/site-packages/pyrobuf/__main__.py", line 20, in main
    install=args.install, proto3=args.proto3)
  File "/usr/lib64/python2.7/site-packages/pyrobuf/__main__.py", line 73, in gen_message
    generate(fname, out, parser, templ_pxd, templ_pyx, generated, pyx_files)
  File "/usr/lib64/python2.7/site-packages/pyrobuf/__main__.py", line 95, in generate
    msgdef = parser.parse_from_filename(fname)
  File "/usr/lib64/python2.7/site-packages/pyrobuf/parse_proto.py", line 198, in parse_from_filename
    return self.parse(s, fname=fname)
  File "/usr/lib64/python2.7/site-packages/pyrobuf/parse_proto.py", line 178, in parse
    rep['messages'].append(self._parse_message(s, token, tokens, messages, enums.copy(), imported['enums']))
  File "/usr/lib64/python2.7/site-packages/pyrobuf/parse_proto.py", line 258, in _parse_message
    current.messages[token.name] = self._parse_message(s, token, tokens, messages, enums.copy(), imported_enums)
  File "/usr/lib64/python2.7/site-packages/pyrobuf/parse_proto.py", line 249, in _parse_message
    token = next(tokens)
  File "/usr/lib64/python2.7/site-packages/pyrobuf/parse_proto.py", line 150, in tokenize
    raise Exception("Unexpected character '%s' in line %d: '%s'" % (s[pos], line, s[pos-10:pos+10]))
Exception: Unexpected character '_' in line 4: 'Underscore_test {
  '
```
Jinja2 version is 2.9.6, in case that matters.

**Comment by tburmeister** [comment]
I've created a PR to fix this, though I would note that underscores in message names violate the Protobuf style guide.

**Comment by vstax** [comment]
@tburmeister Thank you!
Well, it just so happens so some of protobufs that we use contain underscores :)
(I'll test and close issue on Monday if that's OK)

**Comment by tburmeister** [comment]
I just pushed version 0.6.4 to PyPI with this fix.

**Comment by vstax** [comment]
Works fine now.
