### ISSUE TITLE
FileExistsError is not defined on python2

### ISSUE THREAD

**Issue by vstax** [appnexus/pyrobuf#87]
Python 2.7.14, pyrobuf 0.6.3 (latest version from pip). Executing pyrobuf for the second time causes this:
```
$ pyrobuf test.proto
Traceback (most recent call last):
  File "/usr/bin/pyrobuf", line 11, in <module>
    load_entry_point('pyrobuf==0.6.3', 'console_scripts', 'pyrobuf')()
  File "/usr/lib64/python2.7/site-packages/pyrobuf/__main__.py", line 20, in main
    install=args.install, proto3=args.proto3)
  File "/usr/lib64/python2.7/site-packages/pyrobuf/__main__.py", line 53, in gen_message
    except FileExistsError:
NameError: global name 'FileExistsError' is not defined
```

This exception doesn't exist in python2/

**Comment by tburmeister** [comment]
Good catch, thanks.

**Comment by tburmeister** [comment]
Pushed version 0.6.4 with this fix.

**Comment by vstax** [comment]
The fix works, thanks.
