### ISSUE TITLE
throw exception when message name is not begin with an uppercase letter

### ISSUE THREAD

**Issue by slxiao** [appnexus/pyrobuf#93]
For example, 

message mrbts
{
}

Run  pyrobuf mrbts.proto

We will meet the following exception:

mint@mint:~/workspace/nbs$ pyrobuf mrbts.proto
generating mrbts.proto
Traceback (most recent call last):
  File "/usr/local/bin/pyrobuf", line 11, in <module>
    load_entry_point('pyrobuf==0.6.4', 'console_scripts', 'pyrobuf')()
  File "/usr/local/lib/python2.7/dist-packages/pyrobuf/__main__.py", line 25, in main
    install=args.install, proto3=args.proto3)
  File "/usr/local/lib/python2.7/dist-packages/pyrobuf/__main__.py", line 78, in gen_message
    generate(fname, out, parser, templ_pxd, templ_pyx, generated, pyx_files)
  File "/usr/local/lib/python2.7/dist-packages/pyrobuf/__main__.py", line 100, in generate
    msgdef = parser.parse_from_filename(fname)
  File "/usr/local/lib/python2.7/dist-packages/pyrobuf/parse_proto.py", line 198, in parse_from_filename
    return self.parse(s, fname=fname)
  File "/usr/local/lib/python2.7/dist-packages/pyrobuf/parse_proto.py", line 159, in parse
    for token in tokens:
  File "/usr/local/lib/python2.7/dist-packages/pyrobuf/parse_proto.py", line 150, in tokenize
    raise Exception("Unexpected character '%s' in line %d: '%s'" % (s[pos], line, s[pos-10:pos+10]))
Exception: Unexpected character 'm' in line 1: ''

**Comment by tburmeister** [comment]
Pyrobuf currently enforces capitalized message names, as suggested in the Style Guide: https://developers.google.com/protocol-buffers/docs/style

**Comment by slxiao** [comment]
Thanks. I will close this issue.
